name = "what-to-eat"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "what-to-eat-db"
database_id = "85358071-f6d4-4edc-b6a6-ef18eaaaa933"

[[kv_namespaces]]
binding = "KV"
id = "8fe1e59a594c4ed79bd856df403a14a3"

[ai]
binding = "AI"
